version: '3.8'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - pgsql

  php-cli:
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - pgsql

  pgsql:
    image: oroinc/pgsql:13.7-1-alpine
    ports:
      - "5432:5432"
    labels:
      com.symfony.server.service-prefix: ORO_DB
    environment:
      POSTGRES_USER: oro_db_user
      POSTGRES_DB: oro_db
      POSTGRES_PASSWORD: oro_db_pass
      POSTGRES_ROOT_PASSWORD: oro_db_pass
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U$${POSTGRES_USER} -d$${POSTGRES_DB}"
      interval: 5s
      timeout: 30s
      start_period: 40s

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    labels:
      com.symfony.server.service-prefix: ORO_REDIS

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    labels:
      com.symfony.server.service-prefix: ORO_MAILER

volumes:
  postgres: {}
