services:
    _defaults:
        public: true

    IVLab\Bundle\TestBundle\Controller\CategoryController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
